version: "3.8"
services:
  backend:
    build: ./event-sync
    container_name: event-sync
    ports:
      - "8081:8081"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    env_file:
      - .env
    networks:
      - eventnet

  frontend:
    build: ./event-sync-ui
    container_name: event-sync-ui
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - eventnet

networks:
  eventnet:
